#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Rebuild lessons/index.html (the lesson catalog) and harness/results.json
(a snapshot of scores the static results page reads).

Usage:
    uv run scripts/build_index.py
"""
import json
import pathlib
import sqlite3

ROOT = pathlib.Path(__file__).resolve().parent.parent
DB = ROOT / "db" / "progress.db"
INDEX = ROOT / "lessons" / "index.html"
RESULTS_JSON = ROOT / "harness" / "results.json"


def fetch():
    con = sqlite3.connect(DB)
    con.row_factory = sqlite3.Row
    lessons = [dict(r) for r in con.execute(
        "SELECT * FROM lessons ORDER BY year, course_slot, topic")]
    scores = {r["address"]: dict(r) for r in con.execute(
        "SELECT * FROM latest_scores")}
    mastery = [dict(r) for r in con.execute(
        "SELECT * FROM topic_mastery ORDER BY pct ASC")]
    con.close()
    return lessons, scores, mastery


def build_index(lessons, scores):
    rows = []
    for l in lessons:
        s = scores.get(l["address"])
        badge = (f'{s["score_pct"]}% ({s["correct"]}/{s["total"]})'
                 if s else "not attempted")
        rows.append(
            f'<tr><td><code>{l["address"]}</code></td>'
            f'<td><a href="../{l["file"]}">{l["title"]}</a></td>'
            f'<td>Y{l["year"]}</td><td>{badge}</td></tr>'
        )
    html = f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Lesson Index</title>
<style>
 body{{font:16px/1.5 system-ui,sans-serif;max-width:840px;margin:40px auto;padding:0 16px;color:#1a1a2e}}
 h1{{margin-bottom:.2em}} table{{width:100%;border-collapse:collapse;margin-top:1em}}
 th,td{{text-align:left;padding:8px 10px;border-bottom:1px solid #e5e7eb}}
 code{{color:#2d6a4f}} a{{color:#2d6a4f}}
 .nav a{{margin-right:14px}}
</style></head><body>
<h1>Business Degree — Lesson Index</h1>
<p class="nav"><a href="../harness/results.html">→ Results &amp; mastery</a>
<a href="../curriculum/01-year-1.md">→ Year 1 outlines</a></p>
<table><thead><tr><th>Address</th><th>Lesson</th><th>Year</th><th>Latest score</th></tr></thead>
<tbody>{''.join(rows) or '<tr><td colspan=4>No lessons yet.</td></tr>'}</tbody></table>
<p style="color:#6b7280;margin-top:2em">Generated by build_index.py.</p>
</body></html>"""
    INDEX.write_text(html)


def main() -> None:
    lessons, scores, mastery = fetch()
    build_index(lessons, scores)
    RESULTS_JSON.write_text(json.dumps(
        {"scores": list(scores.values()), "mastery": mastery}, indent=2))
    print(f"Wrote {INDEX} and {RESULTS_JSON} ({len(lessons)} lessons)")


if __name__ == "__main__":
    main()
